version: '3.5'

services:
  # BACKEND
  backend:
    build: .
    hostname: backend
    container_name: higload_backend
    environment:
      DEPLOY_ENV: 'PROD'
      LOG_LEVEL: 'INFO'
      DEBUG_MODE: 'False'
      WRITING_PERIOD: 5

      SQLITE_PATH: sqlite/db.sqlite3
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: highload_db
      DB_USER: db_user
      DB_PASSWORD: db_user_password1
    ports:
      - "8080:8080"
    restart: always


  db:
    hostname: db
    container_name: db
    image: mysql:5.7
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci

    environment:
      MYSQL_DATABASE: highload_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_password1
      MYSQL_ROOT_PASSWORD: 4b_PP1s

    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 33060:3306
    restart: always


volumes:
  db_data:
